# Generated by Django 3.0.8 on 2020-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('lineons', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'java'), ('javaScript', 'javaScript'), ('c', 'C'), ('c++', 'C++')], default='python', max_length=100)),
                ('style', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
